### ISSUE TITLE
基于nginx(docker) + clash的Dockerfile

### ISSUE THREAD

**Issue by j5land** [zhengjie9510/openai-proxy#1]
基于nginx(docker) + clash的Dockerfile，准备构建本地可以访问openai.com 的转发容器。
目前clash 和 nginx(docker) 都集成完毕，容器内可以直接访问https://api.openai.com。

但是通过Nginx配置转发时一直超时，咨询下有没有碰到过类似问题。
docker中 Nginx conf配置如下

`error_log  /var/log/nginx/error.log notice;
events {
    worker_connections  16;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;
    sendfile        on;
    keepalive_timeout  65;
    # include /etc/nginx/conf.d/*.conf;

    server {
        listen 80;
	server_name  localhost;
        location /v1 {
            proxy_pass  https://api.openai.com;
            proxy_ssl_server_name on;
            proxy_set_header Host api.openai.com;
            chunked_transfer_encoding off;
            proxy_buffering off;
            proxy_cache off;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
    }
    include /etc/nginx/conf.d/*.conf;
}`

**Comment by zhengjie9510** [comment]
没有遇到过哦，可以注释掉最后一行“include /etc/nginx/conf.d/*.conf;”试试
