### ISSUE TITLE
如何在代理设置openai_key？

### ISSUE THREAD

**Issue by BigPeng** [zhengjie9510/openai-proxy#2]
openai.api_key = api_key，我想把api_key在代理设置好，本地调用不需要再输入，应该如何设置

**Comment by ethanz-code** [comment]
> openai.api_key = api_key，我想把api_key在代理设置好，本地调用不需要再输入，应该如何设置

通过Docker设置环境变量就行，dockerfile docker-compose都可以设置，之后程序里应用直接调用运行时环境变量即可
